SPARK_MASTER_WEBUI_PORT=8888

export SPARK_HOME=$SPARK_HOME
export HADOOP_HOME=$HADOOP_HOME
export MASTER=spark://master:7077
export SCALA_HOME=$SCALA_HOME
export SPARK_MASTER_HOST=master
export SPARK_MASTER_PORT=7077

export JAVA_HOME=/usr/local/jdk1.8.0_341

export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
